/** @type {import('next').NextConfig} */
const nextConfig = {
    reactStrictMode: true,
    compiler: {
        styledComponents: true
    },
    images: {
        domains: [
            'drive.google.com',
            'images.wallpapersden.com',
            'www.pcgamesn.com' ,'warframe-web-assets.nyc3.cdn.digitaloceanspaces.com',
            'wallpapercg.com',
            'images.ctfassets.net',
            'images.igdb.com/',
            'www.adrenaline.com.br',
            'www.gamereactor.pt',
            'www.consolecreatures.com',
            'static.bandainamcoent.eu',
            'sm.ign.com',
            'image.api.playstation.com',
            'assets.xboxservices.com',
            'metroamericas.com',
            'assetsio.reedpopcdn.com',
            'd1lss44hh2trtw.cloudfront.net',
            'www.ultimaficha.com.br',
            'sm.ign.com',
            'staticctf.ubisoft.com',
            'upload.wikimedia.org',
            'images.igdb.com',
            'youtu.be',
            'i.ytimg.com',
            'cdn.akamai.steamstatic.com',
            'assetsio.reedpopcdn.com',
            'cdn.akamai.steamstatic.com',
            'gmedia.playstation.com',
            'img.youtube.com',
            'store-images.s-microsoft.com',
            'image.api.playstation.com',
            'warframe-web-assets.nyc3.cdn.digitaloceanspaces.com',
            'images.nintendolife.com',
            'images8.alphacoders.com',
            'images5.alphacoders.com',
            'www.callofduty.com',
            'cdn.mos.cms.futurecdn.net',
            'cdn.cloudflare.steamstatic.com',
            'www.gameinformer.com',
            'takeown.com',
            'culturedvultures.com',
            'eu-images.contentstack.com',
            'relocker.ru',
            'meups.com.br',
            'assets-prd.ignimgs.com',
            'i0.wp.com',
            'global-uploads.webflow.com',
        ],
    }
}

module.exports = nextConfig
